networks:
  dockerapps-net:
    external: true

services:
  gotify:
    image: gotify/server
    container_name: gotify
    networks:
      dockerapps-net:
        ipv4_address: 172.20.0.16
        ipv6_address: fd00:dead:beef:2::16
    ports:
      - 8081:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GOTIFY_SERVER_PORT=80
    volumes:
      - ./data:/app/data
    restart: unless-stopped