- greeting:
    text_size: xl
    text: My Media Server
- resources: 
    label: System
    expanded: true 
    cpu: true 
    memory: true 
    uptime: true 

- resources:
    label: Storage - Dockerapps
    disk:
      - /app/config

- resources:
    label: Storage - Media
    disk:
     - /mnt/media_disk

- resources:
    label: Storage - Games
    disk:
      - /mnt/games_disk

- resources:
    label: Storage - Library
    disk:
      - /mnt/library_disk
